### ISSUE TITLE
07-04-2018

### ISSUE THREAD

**Issue by chrisvandergeld** [chrisvandergeld/statuspage#1]
PLANNED DURATION: 11HRS (0800-1900). Performing Q1 2018 maintenance. I'll be: 

Upgrading RAM from 48 to 96GB. 

Reconfiguring FTP permissions (Still have to make profiles about who has which permissions). 

Adding a 6 terabyte HDD (Not for the array, for parity). 

Building parity drive. 

Upgrading L5640 CPUs to X5650 CPUs. 

Adding new CPU coolers 

and I'll finally be adding an UPS (Uninterruptible Power Supply) to calculate power usage.

**Comment by Saltystew** [comment]
potato
